### ISSUE TITLE
Vector Package Version Constraint makes cabal install fail

### ISSUE THREAD

**Issue by eceforge** [reactive-systems/icedude#2]
It looks like the constraint in the cabal file sets the max version of the "vector" package at 0.12 which causes cabal to be unable to install anything since the current version of vector is at 0.12.0.1 (and I'm assuming another package requires the use of 0.12.0.1). Looking at the changelog for the vector package (https://hackage.haskell.org/package/vector-0.12.0.1/changelog) shows that the changes are fairly limited. 

I was able to complete the install by changing the iCEDude.cabal line that limits the max vector package from 0.12 to 0.13 (although increasing to 0.12.0.1 is probably a safer bet).

**Comment by kleinreact** [comment]
Thank you for the info. 

I updated the cabal file to support the newer vector package (fixed by 88cbe2a).
